### ISSUE TITLE
How to set 'table_open' rule?

### ISSUE THREAD

**Issue by HiKumho** [digitalmoksha/motion-markdown-it#1]
Hi,

I am trying to add classes for table

In markdown-it.js 
```
md.renderer.rules.table_open = (tokens, idx)->
  return '<table class="table table-striped table-bordered">'
```

In motion-markdown-it, I am trying to do for set it 
```
md.renderer.rules.getRules('table_open') = lambda { return '<table class="table table-striped table-bordered">'  }
```
But it not working

Thanks

**Comment by digitalmoksha** [comment]
@HiKumho, I believe what you need is

```
md.renderer.rules['table_open'] = lambda { return '<table class="table table-striped table-bordered">'  }
```

**Comment by HiKumho** [comment]
@digitalmoksha, Thanks

But it raised ArgumentError
![](http://ogpkf2q99.bkt.clouddn.com/Screenshot.png)

I try to add arguments `|tokens, idx, options, env, renderer|` for lambda, it is ok
